GET http://localhost:8080/tasks

###


GET http://localhost:8080/tasks/5f6d1b20ae08853bf8cdc6d9

###


POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "Dormir temprano",
  "description": "Tener un sueño reparador...."
}

###

DELETE http://localhost:8080/tasks/5f6da42f96eb2d13a06f5730

###

PATCH  http://localhost:8080/tasks/5f6d255296eb2d13a06f572b
Content-Type: application/json

{
  
  "completed": true
  
}
